Feature/poet 3 connect to jira api amend
agiledigital/poet-slack-bot pull request #15
Opened 2016-10-06 05:04 UTC by dongxuDX

1. Complete end to end flow;
2. Keep user credentials in the environment variables.

2016-10-06 09:33 UTC, hasanniz requested changes

2016-10-06 09:33 UTC, hasanniz commented on server/app/controllers/Application.java
> +  public CompletionStage<Result> QA(String query) throws IOException,
Change the action name to something more readable instead of `QA` (question answer?). Like `get(String query)`.

2016-10-06 09:33 UTC, hasanniz commented on server/app/services/JiraInfo.java
> +  public String account;
Rename these to `username` and `password` instead of `account` and `pwd`, and refactor across the codebase.

2016-10-06 09:33 UTC, hasanniz commented on server/app/services/Utils.java
> +   return new JiraInfo(configuration.getString("jira.account"), configuration.getString("jira.pwd"));
`jira.username`, `jira.password`.

2016-10-06 09:33 UTC, hasanniz commented on server/app/services/Utils.java
> +        (new FileWriter("logs/missedQuery.log", true));
I am unsure about manually writing to files. What if file gets corrupted or path doesn't exist? Or what if multiple threads try to access the same file?

2016-10-06 09:33 UTC, hasanniz commented on server/app/services/Utils.java
> +      System.out.println(System.getProperty("user.dir"));
Remove these printlns.

2016-10-06 09:33 UTC, hasanniz commented on server/app/services/languageProcessor/Processor.java
> +    ArrayList<String> about_ = new ArrayList<>();
Why is there an underscore appended in these arraylists?
Also can you explain the purpose of these ArrayLists? I can only see one item in each.

2016-10-06 09:33 UTC, hasanniz commented on server/app/services/languageProcessor/Processor.java
> +    for (ArrayList<String> e: posTagging)
A loop to just log all tags seems useless.

2016-10-06 09:33 UTC, hasanniz commented on server/app/services/languageProcessor/Processor.java
> +  public static HashMap<String, String> posTagging_(Annotation ann){
Rename `ann` to `annotation`.

2016-10-06 09:33 UTC, hasanniz commented on server/app/services/languageProcessor/Processor.java
> +        //Problem here is tat when another noun is found, it replaces the old value
I do not understand this comment. And *`that`.

2016-10-06 09:33 UTC, hasanniz commented on server/app/services/languageProcessor/Processor.java
> +        //posTagging.merge(pos, word, String::concat); //find a merging function
Remove commented code.

2016-10-06 09:33 UTC, hasanniz commented on server/app/services/languageProcessor/Processor.java
> +    while (it.hasNext()) {
What is this loop doing? Looks like only printing key value pairs. Please remove if that's all it does.

2016-10-06 09:33 UTC, hasanniz commented on server/app/services/languageProcessor/Processor.java
> +    //System.out.println("This question is about "+ keyword);
Remove commented code.

2016-10-06 09:33 UTC, hasanniz commented on server/app/services/languageProcessor/Processor.java
> +  public static String QuestionTopicMapping(String keyword){
What is the purpose of this function? It's taking `String keyword` as a parameter and always returns string `ticket`.

2016-10-06 09:33 UTC, hasanniz commented on server/app/services/languageProcessor/TaskMap.java
> +    }catch (NoSuchMethodException e){
move all `catch` here in new lines and add appropriate spaces. So it should become:

```
catch (NoSuchMethodException e) {
  e.printStackTrace();
  return taskMap.parseToJson("fail", ERROR_MSG);
}
catch (InvocationTargetException e) {
  e.printStackTrace();
  return taskMap.parseToJson("fail", ERROR_MSG);
}
catch (IllegalAccessException e) {
  e.printStackTrace();
  return taskMap.parseToJson("fail", ERROR_MSG);
}
catch (NullPointerException e) {
  return taskMap.parseToJson("fail", ERROR_MSG);
}
```

2016-10-06 09:33 UTC, hasanniz commented on server/app/services/languageProcessor/TaskMap.java
> +  public JsonNode description_of_ticket(String ticket, JsonNode responseBody){
`ticket` here is ambiguous, it's not the entire ticket as it's a string which means it's a key. So rename `ticket` to `ticketKey`.

2016-10-06 09:33 UTC, hasanniz commented on server/app/services/languageProcessor/TaskMap.java
> +  public JsonNode assignee_of_ticket(String ticket, JsonNode responseBody){
In the entire codebase I have seen three different formats for functions. 
- `my_test_function`
- `MyTestFunction`
- `myTestFunction`

Please rename it to `assigneeOfTicket` and make sure all functions in the project have correct case and format.

2016-10-06 09:33 UTC, hasanniz commented on server/app/services/languageProcessor/TaskMap.java
> +  public JsonNode assignee_of_ticket(String ticket, JsonNode responseBody){
Also `assignee_of_ticket` does not look like a verb, rename it to `getTicketAssignee` instead.

2016-10-06 09:33 UTC, hasanniz commented on server/app/services/queryHandler/Extractor.java
> +                System.out.println("Check point 1");
Please remove all `System.out.println` from project. It will get too chatty and adds a lot of unnecessary extra code.

2016-10-06 09:33 UTC, hasanniz commented on server/app/services/queryHandler/Extractor.java
> +package services.queryHandler;
Too many extra whitespaces in the file. Please use Intellij's code format tool. From the top menu bar click on `Code` then from the menu click on `Reformat Code`. 
Make sure the indents are set to 2.

2016-10-06 09:33 UTC, hasanniz commented on server/conf/routes
> +GET  /favicon.ico   controllers.Assets.at(path="/public/images", file="favicon.png")
We don't need this here.

2016-10-06 09:33 UTC, hasanniz commented on server/conf/application.conf
> +jira.baseUrl = "https://jira.agiledigital.com.au"
We do not need any defaults here. Nor we need jira endpoint ticket (it's always constant).
We just need the following three (I have renamed for clarity).

```
jira.baseUrl = ${?JIRA_BASE_URL}
jira.username = ${?JIRA_USERNAME}
jira.password = ${?JIRA_PASSWORD}
```

2016-10-06 09:33 UTC, hasanniz commented on server/app/services/queryHandler/QueryHandler.java
> +      jsonNode = services.languageProcessor.TaskMap.questionMapping(question_mapping, ticket_id, responseBody);
Is `ticket_id` is like `POET-1` or actual id? If it's like `POET-1` then according to JIRA it's a key.
So for consistency and clarity rename everywhere where it says ticket id to ticket key. 

(and better use the official term, so if JIRA calls it issue then rename them as issueKey, issueName, etc. instead of using any other term.)

2016-10-06 09:33 UTC, hasanniz commented on server/app/services/queryHandler/QueryHandler.java
> +  private JsonNode processResponse(JsonNode responseBody, String question_mapping, String ticket_id){
How come the parameters have different formats? 
- `responseBody`
- `question_mapping`
- `ticket_id`

Please make them all camel case (first letter lowercase) throughout the app. Same goes for function names, class names, variable names etc.

2016-10-06 09:36 UTC, dxli94 commented on server/app/services/Utils.java
> +        (new FileWriter("logs/missedQuery.log", true));
This method is currently not used.

2016-10-06 09:40 UTC, dongxuDX commented on server/app/controllers/Application.java
> +  public CompletionStage<Result> QA(String query) throws IOException,
fixed

2016-10-06 09:41 UTC, dongxuDX commented on server/app/services/JiraInfo.java
> +  public String account;
fixed

2016-10-06 09:43 UTC, dongxuDX commented on server/app/services/Utils.java
> +      System.out.println(System.getProperty("user.dir"));
fixed

2016-10-06 09:44 UTC, dxli94 commented on server/app/services/languageProcessor/Processor.java
> +    ArrayList<String> about_ = new ArrayList<>();
@sabiipoks

2016-10-06 09:46 UTC, dongxuDX commented on server/app/services/languageProcessor/TaskMap.java
> +  public JsonNode assignee_of_ticket(String ticket, JsonNode responseBody){
@sabiipoks  However, I don't think we can change this. The name here matters.

2016-10-06 09:48 UTC, dongxuDX commented on server/conf/routes
> +GET  /favicon.ico   controllers.Assets.at(path="/public/images", file="favicon.png")
We don't need. However, remove this produces disappointing error message on the server side though it does not influence the flow.

2016-10-06 09:50 UTC, dongxuDX commented on server/conf/application.conf
> +jira.baseUrl = "https://jira.agiledigital.com.au"
We need ticket endPoint. Cause this is used for fetching ticket information only. Later on we need to append other endPoints to construct different URL based on JIRA base URL for other purposes.

2016-10-06 09:52 UTC, dongxuDX commented on server/app/services/queryHandler/QueryHandler.java
> +  private JsonNode processResponse(JsonNode responseBody, String question_mapping, String ticket_id){
Fixed

2016-10-06 11:15 UTC, sabiipoks commented on server/app/services/languageProcessor/Processor.java
> +    ArrayList<String> about_ = new ArrayList<>();
removed arraylist. currently we don't need that.

2016-10-06 11:15 UTC, sabiipoks commented on server/app/services/languageProcessor/Processor.java
> +    for (ArrayList<String> e: posTagging)
remove for-loop

2016-10-06 11:15 UTC, sabiipoks commented on server/app/services/languageProcessor/Processor.java
> +  public static HashMap<String, String> posTagging_(Annotation ann){
fixed

2016-10-06 11:15 UTC, sabiipoks commented on server/app/services/languageProcessor/Processor.java
> +        //posTagging.merge(pos, word, String::concat); //find a merging function
fixed

2016-10-06 11:15 UTC, sabiipoks commented on server/app/services/languageProcessor/Processor.java
> +    while (it.hasNext()) {
removed

2016-10-06 11:16 UTC, sabiipoks commented on server/app/services/languageProcessor/Processor.java
> +  public static String QuestionTopicMapping(String keyword){
removed

2016-10-06 11:16 UTC, sabiipoks commented on server/app/services/languageProcessor/TaskMap.java
> +    }catch (NoSuchMethodException e){
done

2016-10-06 11:16 UTC, sabiipoks commented on server/app/services/languageProcessor/TaskMap.java
> +  public JsonNode description_of_ticket(String ticket, JsonNode responseBody){
done

2016-10-06 11:16 UTC, sabiipoks commented on server/app/services/languageProcessor/TaskMap.java
> +  public JsonNode assignee_of_ticket(String ticket, JsonNode responseBody){
done

2016-10-07 02:23 UTC, hasanniz requested changes

2016-10-07 02:23 UTC, hasanniz commented on server/app/services/languageProcessor/TaskMap.java
> +  public JsonNode description_of_ticket(String ticket, JsonNode responseBody){
*`issueKey`

2016-10-07 02:23 UTC, hasannizamani commented on server/app/services/Utils.java
> +        (new FileWriter("logs/missedQuery.log", true));
If a method is unused then remove the method and all references to it from the codebase.

2016-10-07 02:28 UTC, hasanniz requested changes

2016-10-07 02:28 UTC, hasannizamani commented on server/conf/application.conf
> +jira.username = ${?JIRA_NAME}
The name `JIRA_NAME` doesn't make sense, rename it to `JIRA_USERNAME`

2016-10-07 02:28 UTC, hasannizamani commented on server/conf/application.conf
> +jira.password = ${?JIRA_PWD}
Rename `JIRA_PWD` to `JIRA_PASSWORD`.

2016-10-07 02:28 UTC, hasannizamani commented on server/conf/application.conf
> +jira.endPoint_ticket = ${?JIRA_ENDPOINT_TICKET}
I don't know why we need this to be configurable. The API endpoints are always static, and seems hardly unlikely that someone will deploy this app with a different endpoint to fetch issues.

2016-10-07 02:34 UTC, sabiipoks commented on server/app/services/languageProcessor/TaskMap.java
> +  public JsonNode description_of_ticket(String ticket, JsonNode responseBody){
i changed description_of_ticket to getTicketDescription and ticket to ticketKey yesterday, i don't know why it is not reflecting here. but when i go to the branch and view it i can see the changes.

2016-10-07 02:37 UTC, hasannizamani commented on server/app/services/languageProcessor/TaskMap.java
> +  public JsonNode description_of_ticket(String ticket, JsonNode responseBody){
Instead of `ticket` it should be named as `issue` as that's what JIRA calls it officially.

2016-10-07 02:40 UTC, hasannizamani commented on server/conf/application.conf
> +jira.baseUrl = "https://jira.agiledigital.com.au"
Correct, but the API endpoints do not change, so we don't need to make them configurable.

2016-10-07 06:20 UTC, hasanniz approved these changes

2016-10-07 06:22 UTC, merged